### PR TITLE
WithPermission: remove own props from props

### LINKED ISSUE #10: WithPermission: Warning about unknown prop if used inside menu
There is Warning about unknown prop if used inside menu

`Warning: Unknown prop `resolve` on <a> tag. Remove this prop from the element.`

When used like in example for menu, just with resolve

`const checkPermission = (params) => {
  return true;
};`

`<WithPermission authClient={authClient} resolve={checkPermission}>
            <MenuItem
                containerElement={<Link to="/configuration" />}
                primaryText="Configuration"
                leftIcon={<SettingsIcon />}
                onTouchTap={onMenuTap}
            />
</WithPermission>`

### PR DESCRIPTION
**Pull request by natrim**
- remove own props from props passed to child(ren)
+ pass the stripped props to renderSourceChild

resolves #10

### CODE REVIEW

**Review by djhi — APPROVED** [review]

**Comment by djhi** [comment]
Thanks !

**Comment by leandrooriente** [comment]
Hi @djhi, do you any idea of when the next version will be released? I have the same problem here

**Comment by djhi** [comment]
1.0.3 released :)

**Comment by leandrooriente** [comment]
Thanks 😃

**Pull request merged**
